const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  LOGOUT: "LOGOUT",

  GET_POSTS: "GET_POSTS",
  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_LOVE_POSTS: "GET_LOVE_POSTS",
  GET_REGISTER_POSTS: "GET_REGISTER_POSTS",

  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRICES: "GET_PRICES",
  GET_AREAS: "GET_AREAS",
  GET_PROVINCES: "GET_PROVINCES",

  //users
  GET_USER: "GET_USER",
  GET_USER_FAIL: "GET_USER_FAIL",

  DELETE_LOVE_POST: "DELETE_LOVE_POST",
  ADD_LOVE_POST: "ADD_LOVE_POST",
  DELETE_REGISTER_POST: "DELETE_REGISTER_POST",
  ADD_REGISTER_POST: "ADD_REGISTER_POST",

  GET_POSTS_PRIVATE: "GET_POSTS_PRIVATE",
  EDIT_POSTS_PRIVATE: "EDIT_POSTS_PRIVATE",
  SET_DEFAULT_POSTS_PRIVATE: "SET_DEFAULT_POSTS_PRIVATE",
};

export default actionTypes;
