const actionTypes = {
    LOGIN: "LOGIN",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILED: "REGISTER_FAILED",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",
    LOGOUT: "LOGOUT",

    GET_POSTS: "GET_POSTS",
    GET_POSTS_LIMIT: "GET_POSTS_LIMIT",

    GET_CATEGORIES: "GET_CATEGORIES",
    GET_PRICES: "GET_PRICES",
    GET_AREAS: "GET_AREAS",
    GET_NEW_POSTS: "GET_NEW_POSTS",
    GET_PROVINCES: "GET_PROVINCES",

    //users

    GET_USER: "GET_USER",
    GET_USER_FAIL: "GET_USER_FAIL",
};

export default actionTypes;
